export const icons = [
  'fas fa-adjust',
  'fas fa-bolt',
  'fas fa-camera',
  'fas fa-dice',
  'fas fa-envelope',
  'fas fa-fire',
  'fas fa-ghost',
  'fas fa-heart',
  'fas fa-ice-cream',
  'fas fa-key',
  'fas fa-lemon',
  'fas fa-moon',
  'fas fa-paw',
  'fas fa-rocket',
  'fas fa-star',
  'fas fa-tree',
  'fas fa-umbrella',
  'fas fa-venus',
  'fas fa-wrench',
  'fas fa-yin-yang',
];